export const getCountry = (country) => {
    switch (country) {
        case "IT":
            return "Italia";
        case "US":
            return "Stati Uniti";
        case "GB":
            return "Regno Unito";
        case "DE":
            return "Germania";
        case "FR":
            return "Francia";
        case "ES":
            return "Spagna";
        case "CA":
            return "Canada";
        case "AU":
            return "Australia";
        case "BR":
            return "Brasile";
        case "RU":
            return "Russia";
        case "CN":
            return "Cina";
        case "JP":
            return "Giappone";
        case "IN":
            return "India";
        case "KR":
            return "Corea del Sud";
        case "MX":
            return "Messico";
        case "ZA":
            return "Sudafrica";
        case "AR":
            return "Argentina";
        case "ID":
            return "Indonesia";
        case "NL":
            return "Paesi Bassi";
        case "TR":
            return "Turchia";
        case "CH":
            return "Svizzera";
        case "SE":
            return "Svezia";
        case "AT":
            return "Austria";
        case "BE":
            return "Belgio";
        case "DK":
            return "Danimarca";
        case "NO":
            return "Norvegia";
        case "PL":
            return "Polonia";
        case "CZ":
            return "Repubblica Ceca";
        case "RO":
            return "Romania";
        case "UA":
            return "Ucraina";
        case "IE":
            return "Irlanda";
        case "PT":
            return "Portogallo";
        case "FI":
            return "Finlandia";
        case "GR":
            return "Grecia";
        case "HU":
            return "Ungheria";
        case "MY":
            return "Malesia";
        case "SG":
            return "Singapore";
        case "TH":
            return "Thailandia";
        case "PH":
            return "Filippine";
        case "NZ":
            return "Nuova Zelanda";
        case "SA":
            return "Arabia Saudita";
        case "IL":
            return "Israele";
        case "CL":
            return "Cile";
        case "CO":
            return "Colombia";
        case "PE":
            return "Perù";
        case "VE":
            return "Venezuela";
        case "PK":
            return "Pakistan";
        case "BD":
            return "Bangladesh";
        case "VN":
            return "Vietnam";
        case "AE":
            return "Emirati Arabi Uniti";
        case "TW":
            return "Taiwan";
        case "MA":
            return "Marocco";
        case "TN":
            return "Tunisia";
        case "LY":
            return "Libia";
        case "GH":
            return "Ghana";
        case "NG":
            return "Nigeria";
        case "KE":
            return "Kenya";
        case "ZA":
            return "Sudafrica";
        case "EG":
            return "Egitto";
        case "DZ":
            return "Algeria";
        case "SD":
            return "Sudan";
        case "IQ":
            return "Iraq";
        case "IR":
            return "Iran";
        case "SY":
            return "Siria";
        case "JO":
            return "Giordania";
        case "LB":
            return "Libano";
        case "KW":
            return "Kuwait";
        case "OM":
            return "Oman";
        case "QA":
            return "Qatar";
        case "YE":
            return "Yemen";
        case "AE":
            return "Emirati Arabi Uniti";
        case "BH":
            return "Bahrein";
        case "TR":
            return "Turchia";
        case "AZ":
            return "Azerbaigian";
        case "GE":
            return "Georgia";
        case "AM":
            return "Armenia";
        case "BY":
            return "Bielorussia";
        case "UA":
            return "Ucraina";
        case "MD":
            return "Moldavia";
        case "BG":
            return "Bulgaria";
        case "RS":
            return "Serbia";
        case "ME":
            return "Montenegro";
        case "MK":
            return "Macedonia";
        case "AL":
            return "Albania";
        case "HR":
            return "Croazia";
        case "SI":
            return "Slovenia";
        case "BA":
            return "Bosnia ed Erzegovina";
        case "LT":
            return "Lituania";
        case "LV":
            return "Lettonia";
        case "EE":
            return "Estonia";
        case "CY":
            return "Cipro";
        case "SK":
            return "Slovacchia";
        case "HU":
            return "Ungheria";
        case "AT":
            return "Austria";
        case "CH":
            return "Svizzera";
        case "DE":
            return "Germania";
        case "PL":
            return "Polonia";
        case "CZ":
            return "Repubblica Ceca";
        case "RO":
            return "Romania";
        case "UA":
            return "Ucraina";
        default:
            return "";
    }
};